version: "3"
services:
  app:
    container_name: node_app
    build: .
    image: node_app:v1.0
    depends_on:
      - cache
    environment:
      - CACHE_PORT=6379
      - PORT=9000
    ports:
      - 9000:9000
  cache:
    image: redis
    ports:
      - 6379:6379
    environment:
      - APPENDONLY=yes
    volumes:
      - ./cache:/data
